services:
  - type: web
    name: onion-pulse-ai
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn onion_forecast.wsgi:application --workers 2 --threads 2"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DEBUG
        value: "False"
      - key: HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: SECRET_KEY
        generateValue: true
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://onion-pulse-ai.onrender.com"