# Generated by Django 3.2.25 on 2026-01-09 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('factor_type', models.CharField(choices=[('SEASONAL', 'Seasonal'), ('WEATHER', 'Weather'), ('ECONOMIC', 'Economic'), ('POLICY', 'Government Policy'), ('TRANSPORT', 'Transportation')], max_length=50)),
                ('description', models.TextField()),
                ('impact_score', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('market', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=50)),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('modal_price', models.FloatField()),
                ('arrival_quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('LSTM', 'LSTM Neural Network'), ('RF', 'Random Forest'), ('XGB', 'XGBoost'), ('PROPHET', 'Facebook Prophet')], max_length=50)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('rainfall', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('FARMER', 'Farmer'), ('TRADER', 'Trader'), ('CONSUMER', 'Consumer'), ('GOVERNMENT', 'Government Official'), ('RESEARCHER', 'Researcher')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('preferences', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('forecast_date', models.DateField()),
                ('market', models.CharField(max_length=100)),
                ('predicted_min_price', models.FloatField()),
                ('predicted_max_price', models.FloatField()),
                ('predicted_modal_price', models.FloatField()),
                ('confidence_interval', models.FloatField()),
                ('actual_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forecast_app.predictionmodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='onionprice',
            index=models.Index(fields=['date'], name='forecast_ap_date_ed6ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='onionprice',
            index=models.Index(fields=['market'], name='forecast_ap_market_96484d_idx'),
        ),
        migrations.AddIndex(
            model_name='onionprice',
            index=models.Index(fields=['state'], name='forecast_ap_state_ba4906_idx'),
        ),
    ]
