# Generated by Django 6.0.5 on 2026-06-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('user_type', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('subscribed_to_alerts', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
